Academy/app/controllers/home.py
from flask import Blueprint, render_template, request, jsonify, redirect, \
    url_for, abort
from bson.json_util import dumps
from app.decorators import access_level
from .students import students
from bson import json_util, ObjectId
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, current_user
from ..models import Account
import boto3
import random
from flask import current_app as app
from ..utilities import clean_phone, db, upload_profile_image

blueprint = Blueprint("home", __name__)


@blueprint.route('/', methods=['GET'])
@access_level("student")
def dashboard():
    data = {"students": json_util.loads(students(json=True))}
    return render_template('home.html', **data)


@blueprint.route('/login', methods=['POST', 'GET'])
def login():
    def post():
        data = request.get_json(force=True)
        cell_phone = clean_phone(data['cell_phone'])
        account = db.accounts.find_one({"cell_phone": cell_phone})
        if account:
            hashed = account.get('password')
            if hashed and check_password_hash(hashed, data['password']):
                if login_user(Account(account)):
                    return jsonify({'success': True})
        return jsonify({'success': False}), 400

    if request.method == "POST":
        return post()
    return render_template('login.html', next=request.args.get('next'))


@blueprint.route('/logout', methods=['GET'])
@access_level("student")
def logout():
    logout_user()
    return redirect(url_for('home.login'))


@blueprint.route('/verify', methods=['POST', 'GET'])
def verify():
    if request.method == 'GET':
        return render_template('activate.html')
    client = boto3.client('sns')
    data = request.get_json(force=True)
    cell_phone = clean_phone(data['cell_phone'])
    code = data.get('code')
    account = db.accounts.find_one({"cell_phone": cell_phone})
    if account:
        if code:
            if str(code) == str(account.get('activation_code')):
                login_user(Account(account))
                return json_util.dumps(account)
            else:
                return jsonify(
                    {"success": False,
                     "message": "Incorrect activation code"}), 400
        code = random.randint(111111, 999999)
        name = app.config['DAYCARE_NAME']
        message = "Your activation code for {} is {}".format(name, code)
        client.publish(Message=message, PhoneNumber=cell_phone)
        db.accounts.update({"_id": account['_id']},
                           {"$set": {"activation_code": code}})
        return jsonify({'success': True})
    else:
        return jsonify(
            {"success": False,
             "message": "Could not find account with cell phone"}), 404


@blueprint.route('/settings', methods=['GET'])
def settings():
    return render_template('settings.html')


@blueprint.route('/settings/reset_password', methods=['POST'])
@access_level('student')
def reset_password():
    data = request.get_json(force=True)
    account_id = data['account_id']
    password = data['password']
    if account_id == current_user.get_id():
        hashed_password = generate_password_hash(password)
        db.accounts.update({"_id": ObjectId(account_id)},
                           {"$set": {"password": hashed_password}})
        return jsonify({"success": True})
    return jsonify({"success": False}), 400

@blueprint.route("/<account_type>/<id_>/image", methods=["POST"])
def image(account_type, id_):
    url = upload_profile_image(id_, request.files['file'])
    return dumps({"source": url})

Academy/app/controllers/parents.py
from bson.json_util import dumps
from bson import ObjectId
from flask import Blueprint, request, abort, render_template, url_for
from flask_login import current_user
from datetime import datetime
from app.decorators import access_level
from ..utilities import db, clean_phone

blueprint = Blueprint('parents', __name__, url_prefix='/parents')


@blueprint.route("/", methods=['GET', 'POST'])
def parents(json=False):
    query = {"role": "parent"}

    @access_level("teacher")
    def get():
        data = db.accounts.find(query)
        if request.args.get('json') or json:
            return dumps(data)
        return render_template("parents/parents.html", parents=data)

    @access_level("administrator")
    def post():
        data = request.get_json(force=True)
        data['created'] = datetime.now()
        data['modified'] = datetime.now()
        data['profile_image_url'] = url_for('static',
                                            filename="images/default.png")
        data['role'] = "parent"
        data['cell_phone'] = clean_phone(data['cell_phone'])
        db.accounts.save(data)
        return dumps(data)

    if request.method == "GET":
        return get()
    if request.method == "POST":
        return post()


@blueprint.route("/<parent_id>/students", methods=['GET', 'POST'])
def students(parent_id):
    def post():
        student_id = request.get_json(force=True)['student_id']
        push = {"$push": {"parent_ids": ObjectId(parent_id)}}
        db.accounts.update({"_id": ObjectId(student_id)}, push)
        return dumps({"success": True})

    def get():
        query = {"role": "student", "parent_ids": ObjectId(parent_id)}
        if current_user.role in ['parent']:
            if parent_id != current_user.get_id():
                abort(404)
        return dumps(db.accounts.find(query))

    if request.method == "GET":
        return get()
    if request.method == "POST":
        return post()


@blueprint.route("/<parent_id>", methods=['GET', 'PUT', 'DELETE'])
def parent(parent_id, json=False):
    query = {"_id": ObjectId(parent_id), "role": "parent"}

    @access_level("parent")
    def get():
        data = db.accounts.find_one(query)
        data = data if data else abort(404)
        if request.args.get('json') or json:
            return dumps(data)
        return render_template("parents/parent.html", parent=data)

    @access_level("parent")
    def put():
        data = request.get_json(force=True)
        data['modified'] = datetime.now()
        data['cell_phone'] = clean_phone(data['cell_phone'])
        data['work_phone'] = clean_phone(data['work_phone'])
        db.accounts.update(query, {"$set": data})
        return dumps(data)

    @access_level("administrator")
    def delete():
        db.accounts.delete_one(query)
        return dumps({'success': True})

    if request.method == "GET":
        return get()
    if request.method == "PUT":
        return put()
    if request.method == "DELETE":
        return delete()

Academy/app/controllers/students.py
from bson.json_util import dumps
from bson import ObjectId
from flask import Blueprint, request, abort, render_template, url_for
from flask_login import current_user
from datetime import datetime
from app.decorators import access_level
from ..utilities import db
import boto3

blueprint = Blueprint('students', __name__, url_prefix='/students')


@blueprint.route("/", methods=['GET', 'POST'])
def students(json=False):
    query = {"role": "student"}
    if current_user.role == "parent":
        query['parent_ids'] = ObjectId(current_user.get_id())

    @access_level("parent")
    def get():
        data = dict(students=db.accounts.find(query))
        if request.args.get('json') or json:
            return dumps(data['students'])
        return render_template("students/students.html", **data)

    @access_level("administrator")
    def post():
        data = request.get_json(force=True)
        data['created'] = datetime.now()
        data['modified'] = datetime.now()
        data['role'] = "student"
        data['parent_ids'] = [ObjectId(data['parent_id'])]
        data['profile_image_url'] = url_for('static',
                                            filename="images/default.png")
        db.accounts.save(data)
        return dumps(data)

    if request.method == "GET":
        return get()
    if request.method == "POST":
        return post()


@blueprint.route("/<student_id>", methods=['GET', 'PUT', 'DELETE'])
def student(student_id, json=False):
    query = {"_id": ObjectId(student_id), "role": "student"}
    if current_user.role == "parent":
        query['parent_ids'] = ObjectId(current_user.get_id())

    @access_level("parent")
    def get():
        data = db.accounts.find_one(query)
        data = data if data else abort(404)
        if request.args.get('json') or json:
            return dumps(data)
        return render_template("students/student.html", student=data)

    @access_level("parent")
    def put():
        data = request.get_json(force=True)
        data['modified'] = datetime.now()
        db.accounts.update(query, {"$set": data})
        return dumps(data)

    @access_level("administrator")
    def delete():
        db.accounts.delete_one(query)
        db.reports.delete_many({"student_id": ObjectId(student_id)})
        db.events.delete_many({"student_id": ObjectId(student_id)})
        return dumps({'success': True})

    if request.method == "GET":
        return get()
    if request.method == "PUT":
        return put()
    if request.method == "DELETE":
        return delete()


@blueprint.route("/<student_id>/reports", methods=['GET', 'POST'])
def reports(student_id):
    query = {"_id": ObjectId(student_id)}
    if current_user.role in ['parent']:
        query['parent_ids'] = ObjectId(current_user.get_id())
        if not db.accounts.find_one(query): abort(404)

    @access_level('parent')
    def get():
        data = db.reports.find({"student_id": ObjectId(student_id)})
        return dumps(list(data))

    @access_level('teacher')
    def create():
        data = request.get_json(force=True)
        data['created'] = datetime.now()
        data['modified'] = datetime.now()
        data['created_by'] = ObjectId(current_user.get_id())
        data['student_id'] = ObjectId(student_id)
        db.reports.save(data)
        return dumps(data)

    if request.method == "POST":
        return create()
    elif request.method == "GET":
        return get()


@blueprint.route("/<student_id>/reports/<report_id>",
                 methods=['PUT', 'GET', 'DELETE'])
@access_level()
def report(student_id, report_id):
    query = {"_id": ObjectId(student_id)}
    if current_user.role in ['parent']:
        query['parent_ids'] = ObjectId(current_user.get_id())
        if not db.accounts.find_one(query): abort(404)

    @access_level('parent')
    def get():
        data = dict()
        data['report'] = db.reports.find_one(ObjectId(report_id))
        data['student'] = db.accounts.find_one(ObjectId(student_id))
        template = 'reports/{}.html'.format(data['report']['title'].lower())
        if request.args.get('json'):
            return dumps(data['report'])
        return render_template(template, **data)

    @access_level('teacher')
    def update():
        data = request.get_json(force=True)
        data['modified'] = datetime.now()
        data['modified_by'] = datetime.now()
        db.reports.update({'_id': ObjectId(report_id)}, {"$set": data})
        return dumps(data)

    @access_level('teacher')
    def delete():
        db.reports.delete_one({"_id": ObjectId(report_id)})
        return dumps({'success': True})

    if request.method == "GET":
        return get()
    elif request.method == "PUT":
        return update()
    elif request.method == "DELETE":
        return delete()


@blueprint.route('/<student_id>/reports/<report_id>/events',
                 methods=['POST', 'GET', 'DELETE'])
def events(student_id, report_id):
    query = {"_id": ObjectId(student_id)}
    if current_user.role in ['parent']:
        query['parent_ids'] = ObjectId(current_user.get_id())
        if not db.accounts.find_one(query): abort(404)

    @access_level('student')
    def get_events():
        data = db.events.find({"report_id": ObjectId(report_id)})
        return dumps(list(data))

    @access_level('teacher')
    def create_event():
        data = request.get_json(force=True)
        data['created'] = datetime.now()
        data['modified'] = datetime.now()
        data['student_id'] = ObjectId(student_id)
        data['created_by'] = ObjectId(current_user.id)
        data['report_id'] = ObjectId(report_id)
        db.events.save(data)
        return dumps(data)

    @access_level('teacher')
    def delete_events():
        db.events.delete_many({"report_id": ObjectId(report_id)})
        return dumps({"success": True})

    if request.method == 'GET':
        return get_events()
    elif request.method == 'POST':
        return create_event()
    elif request.method == 'DELETE':
        return delete_events()


@blueprint.route('/<student_id>/reports/<report_id>/events/<event_id>',
                 methods=['GET', 'PUT', 'DELETE'])
def event(student_id, report_id, event_id):
    event_id = ObjectId(event_id)

    @access_level('parent')
    def get_event():
        return dumps(db.events.find_one())

    @access_level('teacher')
    def update_event():
        data = request.get_json(force=True)
        data['modified'] = datetime.now()
        data['modified_by'] = ObjectId(current_user.id)
        db.events.update({'_id': event_id}, {"$set": data})
        return get_event()

    @access_level('teacher')
    def delete_event():
        db.events.delete_one({'_id': event_id})
        return dumps({"success": True})

    if request.method == "GET":
        return get_event()

    elif request.method == "PUT":
        return update_event()

    elif request.method == "DELETE":
        return delete_event()


@blueprint.route('/<student_id>/reports/<report_id>/send', methods=["POST"])
@access_level('teacher')
def report_send(student_id, report_id):
    sns = boto3.client('sns')
    parent_id = request.get_json(force=True)['parent_id']
    parent = db.accounts.find_one(ObjectId(parent_id))
    _student = db.accounts.find_one(ObjectId(student_id))
    message = "{name}'s daily report is now available! {link}"
    url = url_for('students.report', student_id=student_id, report_id=report_id)
    link = request.url_root[:-1] + url

    if parent['_id'] in _student['parent_ids']:
        message = message.format(name=_student['name'], link=link)
        sns.publish(Message=message, PhoneNumber=parent['cell_phone'])
        return dumps({"success": True})
    return dumps({"success": False}), 400


@blueprint.route('/search', methods=["POST"])
@access_level('teacher')
def search():
    name = request.get_json(force=True)['name']
    data = []
    if len(name) > 0:
        query = {'name': {'$regex': name, '$options': 'i'}, 'role': 'student'}
        data = db.accounts.find(query).limit(10)
    return dumps(data)

Academy/app/controllers/teachers.py
from bson.json_util import dumps
from bson import ObjectId
from flask import Blueprint, request, abort, render_template
from flask_login import current_user
from datetime import datetime
from app.decorators import access_level
from ..utilities import db

blueprint = Blueprint('teachers', __name__, url_prefix='/teachers')


@blueprint.route("/", methods=['GET', 'POST'])
def teachers(json=False):
    query = {"role": "student"}
    if current_user.role == "parent":
        query['parent_ids'] = ObjectId(current_user.id)

    @access_level("parent")
    def get():
        data = dict(accounts=db.accounts.find(query))
        data['role'] = "student"
        if request.args.get('json') or json:
            return dumps(data['accounts'])
        return render_template("accounts/list.html", **data)

    def post():
        data = request.get_json(force=True)
        data['created'] = datetime.now()
        data['modified'] = datetime.now()
        data['role'] = "student"
        data['parent_ids'] = [ObjectId(i) for i in data['parent_ids']]
        db.accounts.save(data)
        return dumps(data)

    if request.method == "GET":
        return get()
    if request.method == "POST":
        return post()


@blueprint.route("/<_id>", methods=['GET', 'PUT', 'DELETE'])
def teacher(_id, json=False):
    query = {"_id": ObjectId(_id), "role": "student"}
    if current_user.role == "parent":
        query['parent_ids'] = ObjectId(current_user.id)

    @access_level("parent")
    def get():
        data = db.accounts.find_one(query)
        data = data if data else abort(404)
        if request.args.get('json') or json:
            return dumps(data)
        return render_template("accounts/account.html", account=data)

    @access_level("parent")
    def put():
        data = request.get_json(force=True)
        data['modified'] = datetime.now()
        db.accounts.update(query, {"$set": data})
        return dumps(data)

    @access_level("administrator")
    def delete():
        db.accounts.delete_one(query)
        return dumps({'success': True})

    if request.method == "GET":
        return get()
    if request.method == "PUT":
        return put()
    if request.method == "DELETE":
        return delete()

Academy/app/templates/activate.html
{% extends "base.html" %} {% block title %} Login {% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
	<body class="hold-transition login-page">
	<div class="login-box">
		<div class="login-logo">
			<a href="/"><b>Academy</b>Center</a>
		</div>
		<div class="login-box-body">
			<div class="alert hide"></div>
			<div class="form-group" id="cell-phone">
				<input type="tel" class="form-control" placeholder="Cell Phone">
			</div>
			<div class="form-group hide" id="code">
				<input type="text" class="form-control" placeholder="Verification Code"
				       id="activation-code">
			</div>
			<div class="form-group hide" id="password">
				<input type="password" class="form-control" placeholder="Password">
			</div>
			<div class="form-group hide" id="confirm-password">
				<input type="password" class="form-control"
				       placeholder="Confirm Password">
			</div>
			<button id="send" class="btn bg-aqua btn-block">Send Verification</button>
			<button id="verify" class="btn bg-purple btn-block hide">Verify</button>
			<button id="activate" class="btn bg-green btn-block hide">Activate
			</button>
		</div>
	</div>
	</body>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript">
      var phoneDiv = $('#cell-phone');
      var codeDiv = $('#code');
      var passwordDiv = $('#password');
      var cPasswordDiv = $('#confirm-password');
      var sendButton = $('#send');
      var verifyButton = $('#verify');
      var activateButton = $('#activate');
      var alert = $('.alert');
      var accountId = null;

      sendButton.click(function () {
          var phoneNumber = phoneDiv.find('input').val();
          send_verification(phoneNumber, function () {
              alert.addClass('hide');
              codeDiv.removeClass('hide');
              verifyButton.removeClass('hide');
              phoneDiv.find('input').prop('disabled', true);
              sendButton.hide();
          }, function (response) {
              alert.addClass();
              alert.addClass('alert alert-danger');
              alert.removeClass('hide');
              alert.text(response.responseJSON.message);
          });
      });

      verifyButton.click(function () {
          var phoneNumber = phoneDiv.find('input').val();
          var code = codeDiv.find('input').val();
          verify_account(phoneNumber, code, function (account) {
              passwordDiv.removeClass('hide');
              cPasswordDiv.removeClass('hide');
              activateButton.removeClass('hide');
              codeDiv.find('input').prop('disabled', true);
              verifyButton.hide();
              alert.addClass('hide');
              accountId = account['_id']['$oid'];
          }, function (response) {
              alert.addClass();
              alert.addClass('alert alert-danger');
              alert.removeClass('hide');
              alert.text(response.responseJSON.message);
          });
      });

      activateButton.click(function () {
          var password = passwordDiv.find('input').val();
          var cPassword = cPasswordDiv.find('input').val();
          if (password.length < 8) {
              alert.addClass();
              alert.addClass('alert alert-warning');
              alert.removeClass('hide');
              alert.text("Password must be at least 8 characters long.");
          } else if (password === cPassword) {
              change_password(accountId, password, function () {
                  window.location = "/";
              });
          } else {
              alert.addClass();
              alert.addClass('alert alert-danger');
              alert.removeClass('hide');
              alert.text("Your password's don't match");
          }
      });

	</script>
{% endblock %}

Academy/app/templates/base-nav.html
{% extends "base.html" %}

{% block header %}
	{% block nav %}
		<a href="{{ url_for('home.dashboard') }}" class="logo">
			<span class="logo-mini"><b>FL</b>A</span>
			<span class="logo-lg"><b>FullLife</b>Academy</span>
		</a>
		<nav class="navbar navbar-static-top">
			<a class="sidebar-toggle" data-toggle="offcanvas" role="button">
				<span class="sr-only">Toggle navigation</span>
			</a>
			<div class="navbar-custom-menu">
				<ul class="nav navbar-nav">
					<li>
						<a href="{{ url_for('home.logout') }}">
							<i class="fa fa-sign-out"></i> <span>Logout</span>
							<span class="pull-right-container"></span>
						</a>
					</li>
				</ul>
			</div>
		</nav>
	{% endblock %}
{% endblock %}


{% block sideleft %}
	<aside class="main-sidebar">
		<section class="sidebar">
			<div class="user-panel"
			     onclick="window.location = '/{{ current_user.role }}s/{{ current_user._id }}'">
				<div class="pull-left image">
					<img src="{{ current_user.profile_image_url }}" class="img-circle">
				</div>
				<div class="pull-left info">
					<h4>{{ current_user.name.title() }}</h4>
				</div>
			</div>
			<br>

			<ul class="sidebar-menu">
				<li>
					<a href="{{ url_for('home.dashboard') }}">
						<i class="fa fa-dashboard"></i> <span>Dashboard</span>
						<span class="pull-right-container"></span>
					</a>
				</li>

				{% if current_user.role == 'administrator' %}
{#					<li>#}
{#						<a href="{{ url_for('administrators.administrators') }}">#}
{#							<i class="fa fa-users"></i> <span>Administrators</span>#}
{#							<span class="pull-right-container"></span>#}
{#						</a>#}
{#					</li>#}
{#					<li>#}
{#						<a href="{{ url_for('teachers.teachers') }}">#}
{#							<i class="fa fa-graduation-cap"></i> <span>Teachers</span>#}
{#							<span class="pull-right-container"></span>#}
{#						</a>#}
{#					</li>#}
					<li>
						<a href="{{ url_for('parents.parents') }}">
							<i class="fa fa-male"></i> <span>Parents</span>
							<span class="pull-right-container"></span>
						</a>
					</li>
					<li>

						{% elif current_user.role == 'teacher' %}
					<li>
						<a href="{{ url_for('parents.parents') }}">
							<i class="fa fa-male"></i> <span>Parents</span>
							<span class="pull-right-container"></span>
						</a>
					</li>
				{% endif %}

				<li>
					<a href="{{ url_for('students.students') }}">
						<i class="fa fa-child"></i> <span>Students</span>
						<span class="pull-right-container"></span>
					</a>
				</li>
				<li>
					<a href="/settings">
						<i class="fa fa-wrench"></i> <span>Settings</span>
						<span class="pull-right-container"></span>
					</a>
				</li>

			</ul>
		</section>
	</aside>
{% endblock %}

Academy/app/templates/base.html
<!DOCTYPE html>
<html>
{% block head %}
	<head>
		<meta charset="utf-8">
		<meta name="viewport" id="viewport"
		      content="width=device-width, initial-scale=1">
		<title>AcademyCenter | {% block title %}{% endblock %}</title>
		<link rel="icon"
		      href="{{ url_for('static', filename='images/favicon.png') }}">
		<link rel="apple-touch-icon" href="/static/images/favicon.png">
		{% block styles %}
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/jquery-ui/themes/base/jquery-ui.min.css') }}">
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/adminlte/dist/css/AdminLTE.min.css') }}">
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/adminlte/dist/css/skins/_all-skins.css') }}">
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/fontawesome/css/font-awesome.min.css') }}">
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/jquery-timepicker-wvega/jquery.timepicker.css') }}">
			<link rel="stylesheet" type="text/css"
			      href="{{ url_for('static', filename='bower_components/dropzone/dist/dropzone.css') }}">
			<link rel="stylesheet"
			      href="{{ url_for('static', filename='bower_components/fullcalendar/dist/fullcalendar.css') }}">
			<link rel="stylesheet"
			      href="{{ url_for('static', filename='bower_components/fullcalendar/dist/fullcalendar.print.css') }}"
			      media="print">
		{% endblock %}
	</head>
{% endblock %}
{% block body %}
	<body class="hold-transition skin-green sidebar-mini">
	<div class="wrapper">
		<header class="main-header">
			{% block nav %}
			{% endblock %}
		</header>
		{% block sideleft %}
		{% endblock %}
		<div class="content-wrapper" style="min-height: 638px;">
			{% block content %}
			{% endblock %}
		</div>
		{% block footer %}
			<footer class="main-footer">
				<div class="pull-right hidden-xs">
					<b>Version</b> {{ config['VERSION'] }}
				</div>
				Copyright &copy; 2017 {{ config['DAYCARE_NAME'] }}
			</footer>
		{% endblock %}
	</div>
	</body>
{% endblock %}
{% block scripts %}
	<script
			 src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/moment/moment.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/jquery-timepicker-wvega/jquery.timepicker.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/dropzone/dist/dropzone.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/list.js/dist/list.min.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/fullcalendar/dist/fullcalendar.js') }}"></script>
	<script
			 src="{{ url_for('static', filename='bower_components/adminlte/dist/js/app.js') }}"></script>
	<script src="{{ url_for('static', filename='js/reports.js') }}"></script>
	<script src="{{ url_for('static', filename='js/accounts.js') }}"></script>
	<script src="{{ url_for('static', filename='js/events.js') }}"></script>
{% endblock %}
</html>

Academy/app/templates/home.html
{% extends "base-nav.html" %} {% block title %} Home {% endblock %}

{% block content %}
	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div id="students-box" class="box">
					<div class="box-body" id="student-list">
						<div class="form-group">
							<input class="search form-control" placeholder="Search"/>
						</div>
						<ul class="list list-group accounts"></ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script>
      var studentList = $('#student-list');
      function insert_student(student) {
          var li = $('<li>');
          li.click(function () {
              window.location = "/students/" + student._id;
          });
          li.addClass('info-box box-success');
          var span = $('<span>');
          span.addClass('info-box-icon');
          var img = $('<img>');
          img.addClass('img img-responsive');
          img.attr('src', student.profile_image_url);
          span.append(img);
          var div = $('<div>');
          div.addClass('info-box-content name');
          div.text(student.name);
          li.append(span);
          li.append(div);
          studentList.find('.accounts').append(li)
      }
      get_students(function (students) {
          $.each(students, function (i, student) {
              insert_student(student)
          });
          new List('student-list', {valueNames: ['name']});
      });

	</script>
{% endblock %}

Academy/app/templates/login.html
{% extends "base.html" %} {% block title %} Login {% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
	<body class="hold-transition login-page">
	<div class="login-box">
		<div class="login-logo">
			<a href="/"><b>Academy</b>Center</a>
		</div>
		<div class="login-box-body">
			<div class="form-group">
				<input type="tel" class="form-control" placeholder="Cell Phone"
				       id="cell_phone">
			</div>
			<div class="form-group">
				<input type="password" class="form-control" placeholder="Password"
				       id="password">
			</div>
			<button class="btn bg-green btn-block btn-flat" onclick="login()">
				Sign In
			</button>
			<button class="btn bg-aqua btn-block btn-flat"
			        onclick="window.location = '/verify'">
				Activate
			</button>
		</div>
	</div>
	</body>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript">
      function login() {
          $.ajax({
              type: "POST",
              dataType: "JSON",
              url: "{{ url_for('home.login') }}",
              data: JSON.stringify({
                  cell_phone: $('#cell_phone').val(),
                  password: $('#password').val()
              }),
              success: function () {
		              {% set next_url = next if next else '/' %}
                  window.location = "{{ next_url }}";
              },
              error: function () {
                  $(".login-box-body").effect("shake");
              }
          });
      }
	</script>
{% endblock %}